dist: trusty

language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer install --prefer-dist --ignore-platform-reqs

script:
  - vendor/bin/phpunit
  - vendor/bin/athletic --path test/Benchmark --formatter GroupedFormatter
